### ISSUE TITLE
Module Not Found Error 

### ISSUE THREAD

**Issue by td2334** [CensoredUsername/unrpyc#229] opened 2024-05-26 05:07 UTC
Hi

I'm trying to run the unrpyc program and it keeps coming back with the following. 

Traceback (most recent call last):
  File "/home/trevor/Desktop/unrpyc-master./unrpyc.py", line 48, in <module>
    import decompiler
  File "/home/trevor/Desktop/unrpyc-master./decompiler/__init__.py", line 24, in <module>
    from .renpycompat import renpy
  File "/home/trevor/Desktop/unrpyc-master./decompiler/renpycompat.py", line 26, in <module>
    magic.fake_package("renpy")
  File "/home/trevor/Desktop/unrpyc-master./decompiler/magic.py", line 665, in fake_package
    return __import__(name)
           ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'renpy'

I've spent a good amount of time trying to find a solution but nothing seems to be popping up. I was hoping you could help me with this. Thanks!

**Comment by madeddy** [comment] 2024-05-26 14:50
Your report has important infos missing. Especially version numbers of the used **Python**, **unrpyc** and the target apps Ren'Py should not be missing.

Please read and follow the instructions in the readme-file about making issue reports:
https://github.com/CensoredUsername/unrpyc?tab=readme-ov-file#issue-reports

Greets

**Comment by CensoredUsername** [comment] 2024-05-26 15:44
Likely duplicate of #225.

**Comment by td2334** [comment] 2024-05-26 18:35
> Likely duplicate of #225.

Dev branch worked like a charm thanks for quick reply!

**Comment by madeddy** [comment] 2024-05-26 19:19
> Likely duplicate of #225.

Same thought and why i wanted the version info to be sure.

> Dev branch worked

Good to hear. Have fun.

**Closed** 2024-05-26 20:22 UTC
