### ISSUE TITLE
FakeUnpicklingError and TypeError

### ISSUE THREAD

**Issue by llw12138** [CensoredUsername/unrpyc#149] opened 2022-07-23 07:52 UTC
Error while decompiling C:\Users\25378\Desktop\D\unrpyc-master\work\screens.rpyc:
Traceback (most recent call last):
  File "C:\Users\25378\Desktop\D\unrpyc-master\unrpyc.py", line 202, in worker
    tag_outside_block=args.tag_outside_block, init_offset=args.init_offset, try_harder=args.try_harder)
  File "C:\Users\25378\Desktop\D\unrpyc-master\unrpyc.py", line 165, in decompile_rpyc
    ast = read_ast_from_file(in_file)
  File "C:\Users\25378\Desktop\D\unrpyc-master\unrpyc.py", line 138, in read_ast_from_file
    data, stmts = magic.safe_loads(raw_contents, class_factory, {"_ast", "collections"})
  File "C:\Users\25378\Desktop\D\unrpyc-master\decompiler\magic.py", line 599, in safe_loads
    encoding=encoding, errors=errors).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "C:\Users\25378\Desktop\D\unrpyc-master\decompiler\magic.py", line 113, in __new__
    raise FakeUnpicklingError("{0} was instantiated with unexpected arguments {1}, {2}".format(cls, args, kwargs))
FakeUnpicklingError: <class 'set'> was instantiated with unexpected arguments ([],), {}

Decompiling C:\Users\25378\Desktop\D\unrpyc-master\work\gui.rpyc to C:\Users\25378\Desktop\D\unrpyc-master\work\gui.rpy...
Decompiling C:\Users\25378\Desktop\D\unrpyc-master\work\gallery.rpyc to C:\Users\25378\Desktop\D\unrpyc-master\work\gallery.rpy...
Decompiling C:\Users\25378\Desktop\D\unrpyc-master\work\options.rpyc to C:\Users\25378\Desktop\D\unrpyc-master\work\options.rpy...
Error while decompiling C:\Users\25378\Desktop\D\unrpyc-master\work\script.rpyc:
Traceback (most recent call last):
  File "C:\Users\25378\Desktop\D\unrpyc-master\unrpyc.py", line 202, in worker
    tag_outside_block=args.tag_outside_block, init_offset=args.init_offset, try_harder=args.try_harder)
  File "C:\Users\25378\Desktop\D\unrpyc-master\unrpyc.py", line 165, in decompile_rpyc
    ast = read_ast_from_file(in_file)
  File "C:\Users\25378\Desktop\D\unrpyc-master\unrpyc.py", line 138, in read_ast_from_file
    data, stmts = magic.safe_loads(raw_contents, class_factory, {"_ast", "collections"})
  File "C:\Users\25378\Desktop\D\unrpyc-master\decompiler\magic.py", line 599, in safe_loads
    encoding=encoding, errors=errors).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 1204, in load_setitem
    dict[key] = value
TypeError: 'RevertableDict' object does not support item assignment
-------------------------------------------------------------------------------
你好，我在反编译时出现了这两个问题，这两个问题有办法解决吗？/Hello, I have these two problems during decompilation. Is there any way to solve these two problems?

**Comment by KateJohn** [comment] 2022-07-24 05:56
#146 
一样的问题

**Comment by MARLBORO-NEW** [comment] 2022-10-20 14:39
try: https://github.com/CensoredUsername/unrpyc/issues/156#issue-1416743346

**Comment by madeddy** [comment] 2022-12-04 21:13
Just adding this for completeness and for testing if wished. 
- Kubuntu 22.04.1
- unrpyc v1.1.8 with py2
- game Renpy is v7.5.3

```bash
Decompiling /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/bg/alettaoffice/alettaoffice.rpyc to /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/bg/alettaoffice/alettaoffice.rpy...
Decompiling /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/snow.rpyc to /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/snow.rpy...
Decompiling /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/ch/gen/cuddles.rpyc to /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/ch/gen/cuddles.rpy...
Decompiling /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/ch/cherie/images.rpyc to /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/ch/cherie/images.rpy...
Error while decompiling /home/olli/.xlib/RPG/_test/LoSeSb-22.11.0-pc/rpakit_out/bg/alettaoffice/alettaoffice.rpyc:
Traceback (most recent call last):
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-1.1.8/unrpyc.py", line 202, in worker
tag_outside_block=args.tag_outside_block, init_offset=args.init_offset, try_harder=args.try_harder)
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-1.1.8/unrpyc.py", line 165, in decompile_rpyc
ast = read_ast_from_file(in_file)
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-1.1.8/unrpyc.py", line 138, in read_ast_from_file
data, stmts = magic.safe_loads(raw_contents, class_factory, {"_ast", "collections"})
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-1.1.8/decompiler/magic.py", line 599, in safe_loads
encoding=encoding, errors=errors).load()
File "/usr/lib/python2.7/pickle.py", line 864, in load
dispatch[key](self)
File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
value = func(*args)
File "/home/olli/Code/rpy_tools/unrpyc/unrpyc-1.1.8/decompiler/magic.py", line 113, in __new__
raise FakeUnpicklingError("{0} was instantiated with unexpected arguments {1}, {2}".format(cls, args, kwargs))
FakeUnpicklingError: <class 'set'> was instantiated with unexpected arguments ([],), {}
```
[alettaoffice.zip](https://github.com/CensoredUsername/unrpyc/files/10149468/alettaoffice.zip)

**Comment by CensoredUsername** [comment] 2023-11-03 14:52
as @madeddy said, closing this as a duplicate of #146

**Closed by CensoredUsername** 2023-11-03 14:52 UTC
