### ISSUE TITLE
Silent decompilation failure?

### ISSUE THREAD

**Issue by Divers102** [CensoredUsername/unrpyc#110] opened 2021-01-19 05:44 UTC
The game VIRTUES-v9-pc extracted the file, the scripts folder appeared and there the extracted rpy + log unrpyc.log
![До](https://user-images.githubusercontent.com/60133308/104992369-b8d15500-5a42-11eb-8fd7-65ca8c9ffd1d.JPG)
![После](https://user-images.githubusercontent.com/60133308/104992371-ba028200-5a42-11eb-8bcb-6f023a35b008.JPG)
[unrpyc.log.txt](https://github.com/CensoredUsername/unrpyc/files/5833831/unrpyc.log.txt)

Cuntswell game does not allow to extract rpy files + one more log.
![123](https://user-images.githubusercontent.com/60133308/104992447-df8f8b80-5a42-11eb-9bb5-602dcff952d2.JPG)
[unrpyc.log.txt](https://github.com/CensoredUsername/unrpyc/files/5833853/unrpyc.log.txt)

Some games do not allow you to extract files, while others extract well, but there are games with extracted files.

**Comment by CensoredUsername** [comment] 2021-01-19 18:48
I think there's some translation issues because I'm not sure what the actual problem is. The first game seems to have extracted fine, it just keeps all its scripts in the `scrips` folder. I'm somewhat confused about what happened with the second game. un.rpyc seems to have ran successfully, it just didn't find any script files. This is either due to a change in internal ren'py machinery or because the game messes with the internal API that un.rpyc is using. Could you try using normal unpacking tools (like unrpa or rpatool) to extract the rpyc files and then just run them through unrpyc as a command line tool to confirm if the problem is with the rpyc files itself or with the game code?

**Comment by Divers102** [comment] 2021-01-19 19:59
unrpyc to also throw in the games folder?
and I did not understand where to throw the rpatool file, I already tried,
But I have not tried it on unrpa yet.

**Comment by Divers102** [comment] 2021-01-19 20:30
I almost forgot to add information in short, I created an empty file in the games options folder, and at the same time there was your un.rpyc file, and after I started the game and then I saw that information about the game appeared in the options file.

**Comment by Divers102** [comment] 2021-01-19 20:39
I almost forgot to add some information shortly, I created an empty file in the games options.rpy folder, and at the same time your un.rpyc file was there, and after I started the game, I saw this game information appeared in the options.rpy file.

**Comment by Divers102** [comment] 2021-01-19 20:47
I almost forgot, so I created options.rpy file empty and at the same time there was your un.rpyc file And when I started the game and then closed, after the file options.rpy was not empty.

**Comment by CensoredUsername** [comment] 2021-01-19 21:51
no, check the readme for instructions on how to use unrpyc normally.

**Comment by Divers102** [comment] 2021-01-20 08:30
unrpyc also in the games folder if so? I didn't notice any action

**Comment by CensoredUsername** [comment] 2021-01-20 13:16
I have no idea what you are trying to say.

**Comment by CensoredUsername** [comment] 2021-02-22 13:35
Closing due to lack of (coherent) response.

**Closed by CensoredUsername** 2021-02-22 13:36 UTC
