### ISSUE TITLE
TypeError: 'RevertableDict' object does not support item assignment

### ISSUE THREAD

**Issue by NotAsea** [CensoredUsername/unrpyc#168] opened 2023-04-21 08:27 UTC
I've already applied pull [154](https://github.com/CensoredUsername/unrpyc/pull/154) and pull [161](https://github.com/CensoredUsername/unrpyc/pull/161), but still  get no luck, it still throw known error like `TypeError: 'RevertableDict' object does not support item assignment` or ` AttributeError: 'RevertableList' object has no attribute 'extend'`

callstack: 
```cmd
Failed at decompiling D:\H\Games\LoSeSb-23.3.0-pc\game\ac/sleep.rpyc
Traceback (most recent call last):
  File "<unrpyc>", line 40, in decompile_game
  File "<unrpyc>", line 32, in decompile_rpyc
  File "<unrpyc>", line 27, in read_ast_from_file
  File "<magic>", line 143, in safe_loads
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 864, in load
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 1204, in load_setitem
TypeError: 'RevertableDict' object does not support item assignment

Failed at decompiling D:\H\Games\LoSeSb-23.3.0-pc\game\bg/forest/forest.rpyc
Traceback (most recent call last):
  File "<unrpyc>", line 40, in decompile_game
  File "<unrpyc>", line 32, in decompile_rpyc
  File "<unrpyc>", line 27, in read_ast_from_file
  File "<magic>", line 143, in safe_loads
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 864, in load
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 1195, in load_appends
AttributeError: 'RevertableList' object has no attribute 'extend'

```

**Comment by madeddy** [comment] 2023-04-22 00:22
1. Your issue report is insufficient. e.g. You didn even mention which RenPy version the app runs, your OS, ...  This stuff is really important. Read this please: https://github.com/CensoredUsername/unrpyc#when-making-an-issue-report**
2. I believe in your try something went wrong.
- If you applied both pull requests to the same unrpyc i am not surprised. (?)
- Otherwise it's something else, because i tested it with my pull request version from #161 and decompiled your game in question _without a glitch_. Maybe you want to try just the complete version(no changes needed): https://github.com/madeddy/unrpyc/tree/Renpy_8_7.5_compat_fix%40v1.1.8

**Comment by TenchiMuyo1984** [comment] 2023-08-23 21:17
I've the same issue

Versions:
- un.rpyc: 1.1.8
- Ren'py (based on `vc_versions.py`); `version = u'7.6.1.23060707'`

What I've done:
1. I copied the `un-rpyc` file into the `game` directory
2. started the game

Game:
`APromiseBestLeftUnkept-0.9.3-pc`


From `unrpyc.log.txt`
```py
Traceback (most recent call last):
  File "<unrpyc>", line 40, in decompile_game
  File "<unrpyc>", line 32, in decompile_rpyc
  File "<unrpyc>", line 27, in read_ast_from_file
  File "<magic>", line 143, in safe_loads
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 864, in load
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 1212, in load_setitems
TypeError: 'RevertableDict' object does not support item assignment
...
Traceback (most recent call last):
  File "<unrpyc>", line 40, in decompile_game
  File "<unrpyc>", line 32, in decompile_rpyc
  File "<unrpyc>", line 27, in read_ast_from_file
  File "<magic>", line 143, in safe_loads
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 864, in load
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 1139, in load_reduce
  File "<magic>", line 24, in __new__
FakeUnpicklingError: <class 'set'> was instantiated with unexpected arguments ([],), {}
...
Traceback (most recent call last):
  File "<unrpyc>", line 40, in decompile_game
  File "<unrpyc>", line 32, in decompile_rpyc
  File "<unrpyc>", line 27, in read_ast_from_file
  File "<magic>", line 143, in safe_loads
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 864, in load
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/pickle.py", line 1195, in load_appends
AttributeError: 'RevertableList' object has no attribute 'extend'
```

**Comment by madeddy** [comment] 2023-08-26 20:10
> I've the same issue
> 
> Versions:
> 
>     * un.rpyc: 1.1.8

Original unrpyc v1.1.8 does NOT support RenPy versions above 7.4.x !(Means **no** 7.5.x / 7.6.x / 8.0.x / 8.1.x)

**Comment by NotAsea** [comment] 2023-11-04 11:44
@madeddy i'm sorry but, how can i use your fork to build rpy, rpyc file, i try build it like normal (which mean use picklemagic of master branch), but i still cannot decompile game, worse renpy even refuse to load un.rpy file

**Comment by NotAsea** [comment] 2023-11-04 11:51
more report, use un.rpy file from your folk (mention above), it suffer old error `UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 1: ordinal not in range(128)`

**Comment by CensoredUsername** [comment] 2024-02-12 03:50
Seems to be a duplicate of #146, might be resolved on the dev branch now. Feel free to give it a spin!

**Comment by CensoredUsername** [comment] 2024-02-20 10:12
Should be fixed in the current release, please reopen if it isn't.

**Closed by CensoredUsername** 2024-02-20 10:12 UTC
Labels: Ren'py 7 and below, Possibly resolved
