### ISSUE TITLE
When I try to unpack the game, an error pops up.

### ISSUE THREAD

**Issue by Memfivosfey** [CensoredUsername/unrpyc#163] opened 2023-01-20 19:55 UTC
Good day.

Sorry, this may have been the problem before. But when I start the game, it does not unpack the RPYC files, it writes an error.

here is the traceback.txt file, 
https://disk.yandex.com/d/9yzjVDkpMWllSA

the file is just too big.

Here,
https://disk.yandex.com/d/I6tMnomJMZpQCg

  I posted some files from the game, from the "renpy" folder, which the error points to.

and some files from the "game" folder that can't be unpacked.

I beg you, tell me how to unpack this game. Or advise where to find a solution. I would be very grateful.

**Comment by madeddy** [comment] 2023-02-25 10:38
Apps with RenPy newer as v7.4.x versions, such as 7.5+ and 8.0+, are not supported _yet_ by "unrpyc". 

If you want you can try updated unrpyc (test-)forks like this here:
https://github.com/VepsrP/UnRen-Gideon-mod-
OR my variant to find here:
https://github.com/madeddy/unrpyc/tree/py3_v1.1.8

No guarantee! Good luck.

**Comment by rado84-github** [comment] 2023-05-30 18:51
> Good day.
> 
> Sorry, this may have been the problem before. But when I start the game, it does not unpack the RPYC files, it writes an error.
> 
> here is the traceback.txt file, https://disk.yandex.com/d/9yzjVDkpMWllSA
> 
> the file is just too big.
> 
> Here, https://disk.yandex.com/d/I6tMnomJMZpQCg
> 
> I posted some files from the game, from the "renpy" folder, which the error points to.
> 
> and some files from the "game" folder that can't be unpacked.
> 
> I beg you, tell me how to unpack this game. Or advise where to find a solution. I would be very grateful.

Rpyc files are not archives, you can't unpack them. You can only unpack rpa files (which stands for RenPyArchive) but you need rpatool for that, not unrpyc.

**Comment by CensoredUsername** [comment] 2023-11-03 15:13
un.rpy seems to not be loadable in ren'py 8 for now. Duplicate of #92

**Comment by CensoredUsername** [comment] 2024-02-22 02:50
These files are decompileable now with unrpyc, but I still need to update un.rypc so for now you can only use the command line tool.

**Comment by CensoredUsername** [comment] 2024-03-06 02:18
Should be working in the last `un.rpyc` release as well, so closing 🎉

**Closed by CensoredUsername** 2024-03-06 02:18 UTC
Labels: Ren'py 8, Possibly resolved
