### ISSUE TITLE
Unknown AST Node errors when decompiling

### ISSUE THREAD

**Issue by FaceCrap** [CensoredUsername/unrpyc#171] opened 2023-10-28 03:48 UTC
Not sure if this is going to be read, seems there's a lot of open issues. Even less sure if this get's fixed.

I'm getting Unknown AST Node errors decompiling .rpyc files from [Between Humanity](https://f95zone.to/threads/between-humanity-v0-1-1-debatingpanda.177547/) which is a Ren'Py version 8.1.3 game running on Windows 10

this one `pass # <<<COULD NOT DECOMPILE: Unknown AST node: <class 'renpy.sl2.slast.SLContinue'>>>>`
and this `pass # <<<COULD NOT DECOMPILE: Unknown AST node: <class 'renpy.sl2.slast.SLBreak'>>>>`

**Comment by CensoredUsername** [comment] 2023-11-03 00:04
>Not sure if this is going to be read, seems there's a lot of open issues. Even less sure if this get's fixed.

Sorry about that, life's been too busy lately. The issue is appreciated though, I hope to be able to fix all the accumulated issues eventually. For this one, Ren'py likely added some screen language statement that's as of yet unsupported.

**Comment by madeddy** [comment] 2024-02-07 22:26
Sry about the late reply.

> Not sure if this is going to be read, seems there's a lot of open issues. Even less sure if this get's fixed.

Its as @CensoredUsername said.
This are just a few new statements Ren'Py added along with one called "camera". I think i resolved them already in my local copy and commit them if time allows. (Have to work on some old stuff first.)

Greets

**Comment by CensoredUsername** [comment] 2024-02-18 01:34
This has been fixed on dev for ren'py 7, and with the python 3 port it should make it to python 8.

**Comment by CensoredUsername** [comment] 2024-02-20 10:11
Should be fixed in the current release, please reopen if it isn't.

**Closed by CensoredUsername** 2024-02-20 10:11 UTC
Labels: Ren'py 8, Possibly resolved
